[package]
name = "pyncare"
version = "0.1.0"
edition = "2021"

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
config = {path = "../config"}
equilibrium = {path = "../equilibrium"}
pyo3 = { version = "0.27.1", features = ["extension-module", "abi3-py314"] }
