[package]
name = "poincare"
version = "0.1.0"
edition = "2024"
authors = {workspace = true}

[dependencies]
ndarray = {workspace = true}
thiserror = {workspace = true}
utils = {path = "../utils"}
particle = {path = "../particle"}
